# x=input()*2# print(len(x))
# print(x)# n= int(input()) #n=4  последняя квартира не этаже# k= int(input())
# #k=100  номер квартиры, где живёт бабушка# c= int(input())
# #c=9  количество этажей# x=k//n
# #x=25 этажи# z=(x//c)+int(bool(x%c))
# z=3 подъезды# y=(x%c)# # print(k//n+int(bool(k % n)))# print((k//n),(x//c)+int(bool(x%c)),(y%c))
# print(z,y)# a = int(input())# ввести шестизначное число
# if len(str(a))==6:#если строка ровна 6 знакам#     if a % 3 == 0 or a % 5 == 0: #если полученный остаток от деления ровняется 3 или полученный остаток от деления ровняется 5
# print("Таня")# else:
# print("Даша")# else: print("Ввели не шестизначное число")
# иначе ввывести# a= int(input())
# b= int(input())# d= int(input())
# f= int(input())# n= (a//b)
# z= (a%b)# if n==d and z==f: print("Да")
# else: print("Нет")# a= str(input())
# l=len(str(a))# if l>=10 and l%2 ==0: print("Да")
# else: print("Нет")#a= str(input())
# if input()in ("Информатика","Программирование","информатика","программирование"): print("")# else:print("Киплена") 
# a="Красный".lower()
# b="Зелёный".lower() 
# c="Синий".lower()
# color1= input().lower() color2= input().lower()
# if color1+color2 in( a+b, b+a) : print("Коричневый")
# elif color1+color2 in( a+c,c+a): print("Голубой")
# elif color1+color2 in( c+b,c+b): print("Фиолетовый")
# else: print("Неправильный")a=float(input())# if 7.00 <= a <=13.00 or 15.00 <= a < 19.00 : print("Идти в пекарню")
# elif 8.00 <= a <=14.00 or 16.00 <= a < 20.00 : print("Идти в супермаркет")
# elif 8.00 <= a <=24.00: print("Идти в гипермаркет")# else: print("Ждать 7:00")
# x=input('Имя: ')# z=input("Отчество: ")
# t=input('Дата: ')# y=input("Время: ")
# print('Уважаемый(ая)',x ,z +",","Вы приглашены в школу",t,'в',y+'.')
# print(f'Уважаемый(ая) {x} {z}, Вы приглашены в школу {t} в {y}.')# x=int(input())
# if x %2 == 0: print("отжиматься")# else:print("Подтягиваться")
# x=input()
# x=input()if x in {'a', 'e', 'i','o' , 'u'}:print('буква гласная')
# import math
# x=float(input())
# y=float(input())
# if y != 0: 
#     from math import tan, e
#     z = (3+ e ** (y-1))/(1+x*x *abs (y -tan(x)))
#     print(round(z,2))
#     z= (y -abs(x)**.5 )*(x-y/(x+x*x/4))
#     print(round(z,2)) 
# else: print('на ноль делить нельзя')
# k=("Камень")
# n=("Ножницы")
# b=("Бумага")
# color1= input(Миша: )
# color2= input(Ева: )
# if color1.lower > color2.lower in (k>n,n>b,b>k):print("Миша")
# elif color1.lower > color2.lower in (k==k,n==n,b==b):print("Миша")
# else: print("Ева")
x=input()
if x.lower in {'a', 'e', 'i','o' , 'u','а'}:print('буква гласная')
elif x.lower in {'y'}:print('эта буква может быть как гласной, так и согласной')
else:print("Согласная")